CREATE TABLE IF NOT EXISTS users (
    uid INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(30) UNIQUE,
    password CHAR(60) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS drives (
    drive_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(32) UNIQUE NOT NULL,
    user INTEGER,
    password CHAR(60),

    FOREIGN KEY (user) 
        REFERENCES users (uid) 
            ON DELETE CASCADE

);
